owner: leftshiftlogical
repo: status
user-agent: leftshift-bot
sites:
  - name: leftshift.com
    url: https://www.leftshift.com
  - name: Commute API
    url: https://commuteapi.com/healthcheck
assignees:
  - fcjr
status-website:
  cname: status.leftshift.com
  logoUrl: https://raw.githubusercontent.com/leftshiftlogical/status/master/static/img/logo.png
  favicon: https://raw.githubusercontent.com/leftshiftlogical/status/favicon-32x32.png
  name: Leftshift Logical Status
  logoHref: https://www.leftshift.com